name: Solar Theme
url: http://example.org
description: Animation | Commic | Web | Mobile

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
